infodir=/opt/arch/share/info
filelist=(coreutils.info)

post_install() {
 [ -x opt/arch/bin/install-info ] || return 0
 for file in ${filelist[@]}; do
    opt/arch/bin/install-info $infodir/$file $infodir/dir 2> /dev/null
 done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
 [ -x opt/arch/bin/install-info ] || return 0
  for file in ${filelist[@]}; do
    opt/arch/bin/install-info --delete $infodir/$file $infodir/dir 2> /dev/null
  done
}

