info_dir=/opt/arch/share/info
info_files=(bash.info)

post_install() {
  [ -x opt/arch/bin/install-info ] || return 0
  for f in ${info_files[@]}; do
    opt/arch/bin/install-info ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}

post_upgrade() {
  post_install $1
}

pre_remove() {
  [ -x opt/arch/bin/install-info ] || return 0
  for f in ${info_files[@]}; do
    opt/arch/bin/install-info --delete ${info_dir}/$f.gz ${info_dir}/dir 2> /dev/null
  done
}
# vim:set ts=2 sw=2 et:
